### ISSUE TITLE
Stream not running

### ISSUE THREAD

**Issue by SwiftyFlow** [Dhi13man/speed_ometer#1]
Trying to use your project as a tutorial to include a speedometer in my app...

I stripped any Text to Speech as I don't need that and the app wasn't running otherwise. I also targeted the latest Geolocator.

BUT the StreamBuilder does not continuously run. I get in the _onAccelerate only once and then nothing.

AND that the exact same issue I was facing before by trying my own way and before to find yours.

Any idea and can you make your example run well nowadays?

**Comment by Dhi13man** [comment]
Won't be able to dedicate much time to this right now as it was an early career learning project. But I [made fixes and updated the code for Flutter 2 and null safety](https://github.com/Dhi13man/speed_ometer/pull/2). Please check and contribute too if you have the time.

PR <https://github.com/Dhi13man/speed_ometer/pull/2>

**Comment by Dhi13man** [comment]
Closing. Will reopen if there are lingering issues.

**Comment by SwiftyFlow** [comment]
Back at it today/now... I'll comment any findings. Thanks for your bit of time and trial mate!
